export const GET_POKEMONS_REQUEST = 'GET_POKEMONS_REQUEST';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_FAIL = 'GET_POKEMONS_FAIL';

export const GET_POKEMON_DETAILS_REQUEST = 'GET_POKEMON_DETAILS_REQUEST';
export const GET_POKEMON_DETAILS_SUCCESS = 'GET_POKEMON_DETAILS_SUCCESS';
export const GET_POKEMON_DETAILS_FAIL = 'GET_POKEMON_DETAILS_FAIL';
export const GET_POKEMON_DETAILS_RESET = 'GET_POKEMON_DETAILS_RESET';